"""add_exchange_credentials_table

Revision ID: 6ac7f6fb18a3
Revises: acca82f7108e
Create Date: 2026-05-08 17:49:42.878310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac7f6fb18a3'
down_revision: Union[str, Sequence[str], None] = 'acca82f7108e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('integration_logs_timestamp_idx'), table_name='integration_logs')
    # ### end Alembic commands ###
    
    # Create exchange_credentials table
    op.create_table(
        'exchange_credentials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile', sa.String(), nullable=True),
        sa.Column('exchange', sa.String(), nullable=True),
        sa.Column('api_key', sa.String(), nullable=True),
        sa.Column('api_secret', sa.String(), nullable=True),
        sa.Column('base_url', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_credentials_profile'), 'exchange_credentials', ['profile'], unique=True)
    
    # Seed data
    from app.core.config import settings
    from app.core.encryption import encrypt
    
    if settings.EXCHANGE_API_KEY and settings.EXCHANGE_API_KEY != "your_bybit_api_key_here":
        op.execute(f"""
            INSERT INTO exchange_credentials (profile, exchange, api_key, api_secret, is_active)
            VALUES ('live', '{settings.EXCHANGE_NAME}', '{encrypt(settings.EXCHANGE_API_KEY)}',
                    '{encrypt(settings.EXCHANGE_API_SECRET)}', false)
            ON CONFLICT (profile) DO NOTHING;
        """)

    if getattr(settings, 'EXCHANGE_DEMO_API_KEY', ''):
        op.execute(f"""
            INSERT INTO exchange_credentials (profile, exchange, api_key, api_secret, is_active)
            VALUES ('demo', '{settings.EXCHANGE_NAME}', '{encrypt(settings.EXCHANGE_DEMO_API_KEY)}',
                    '{encrypt(settings.EXCHANGE_DEMO_API_SECRET)}', true)
            ON CONFLICT (profile) DO NOTHING;
        """)

def downgrade() -> None:
    """Downgrade schema."""
    # Drop exchange_credentials table
    op.drop_index(op.f('ix_exchange_credentials_profile'), table_name='exchange_credentials')
    op.drop_table('exchange_credentials')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('integration_logs_timestamp_idx'), 'integration_logs', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
