"""setup_system_logs

Revision ID: 9b031e9d4e05
Revises: 
Create Date: 2026-04-22 12:33:57.062547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b031e9d4e05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_id'), 'integration_logs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_logs_timestamp'), 'integration_logs', ['timestamp'], unique=False)
    op.create_index('ix_integration_logs_timestamp_service', 'integration_logs', ['timestamp', 'service_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_logs_timestamp_service', table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_timestamp'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    # ### end Alembic commands ###
