"""add_observability_and_settings_tables

Revision ID: 9feaf8499e20
Revises: 6ac7f6fb18a3
Create Date: 2026-05-09 09:04:25.450387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9feaf8499e20'
down_revision: Union[str, Sequence[str], None] = '6ac7f6fb18a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('integration_logs_timestamp_idx'), table_name='integration_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('integration_logs_timestamp_idx'), 'integration_logs', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
