"""fix_integration_logs_pk_for_timescale

Revision ID: acca82f7108e
Revises: 9b031e9d4e05
Create Date: 2026-04-22 13:13:00.727758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acca82f7108e'
down_revision: Union[str, Sequence[str], None] = '9b031e9d4e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integration_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
    # Manually added: Drop old PK and create new composite PK
    op.drop_constraint('integration_logs_pkey', 'integration_logs', type_='primary')
    op.create_primary_key('integration_logs_pkey', 'integration_logs', ['id', 'timestamp'])

    op.drop_index(op.f('ix_integration_logs_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_timestamp'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_timestamp_service'), table_name='integration_logs')
    op.create_index('ix_integration_logs_service_status', 'integration_logs', ['service_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_logs_service_status', table_name='integration_logs')
    op.create_index(op.f('ix_integration_logs_timestamp_service'), 'integration_logs', ['timestamp', 'service_type'], unique=False)
    op.create_index(op.f('ix_integration_logs_timestamp'), 'integration_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_integration_logs_id'), 'integration_logs', ['id'], unique=False)
    op.alter_column('integration_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
