"""add agent_name to prompt_logs

Revision ID: c08fce7a55e1
Revises: 9feaf8499e20
Create Date: 2026-05-09 09:22:39.428978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08fce7a55e1'
down_revision: Union[str, Sequence[str], None] = '9feaf8499e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_logs', sa.Column('agent_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_prompt_logs_agent_name'), 'prompt_logs', ['agent_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_logs_agent_name'), table_name='prompt_logs')
    op.drop_column('prompt_logs', 'agent_name')
    # ### end Alembic commands ###
